# 自适应因子权重配置文件
# 替代硬编码权重，支持ML训练的动态权重

# 简化的权重学习配置
weight_learning:
  enabled: true
  lookback_days: 252          # 历史数据回看期（天）
  min_confidence: 0.6         # 最小置信度阈值
  max_weight: 0.4             # 单因子最大权重（降低）
  min_weight: 0.05            # 单因子最小权重
  rebalance_frequency: 21     # 权重更新频率（天）

# 简化的因子权重回退配置
fallback_weights:
  momentum: 0.35              # 动量信号
  mean_reversion: 0.35        # 均值回归信号
  quality: 0.30               # 质量信号

# 简化的BMA模型权重配置
bma_weights:
  # 简化IC阈值（只保留3个等级）
  ic_thresholds:
    strong: 0.1        # 强信号阈值
    weak: 0.05         # 弱信号阈值
    noise: 0.02        # 噪音阈值
  
  # 简化权重映射
  weight_mapping:
    strong: 0.4        # 强信号权重
    weak: 0.2          # 弱信号权重  
    noise: 0.0         # 噪音权重
  
  # 基础模型权重
  base_models:
    ridge: 0.3
    xgboost: 0.4
    lightgbm: 0.3

# 简化的缓存配置 - 只保留必要的权重缓存
storage:
  cache_dir: "cache/factor_weights"
  max_history_records: 20         # 减少历史记录
  cleanup_frequency_days: 3       # 更频繁清理
  # REMOVED: backup_enabled - 减少磁盘I/O开销

# 简化的监控配置 - 只保留关键错误日志
monitoring:
  log_weight_changes: false       # 关闭详细权重日志
  performance_tracking: false     # 关闭性能跟踪
  # REMOVED: 详细监控 - 减少CPU和磁盘开销
  
# 精简的调试配置
debug:
  verbose_logging: false          # 关闭详细日志
  save_intermediate_results: false # 关闭中间结果保存
  # REMOVED: 权重模拟 - 减少计算负担