# 延迟数据模式Alpha配置 - 仅使用技术因子
# 适用于无基本面数据访问权限的情况

data_mode: delayed  # 延迟数据模式

polygon_settings:
  # 数据类型设置
  use_realtime_data: false           # 禁用实时数据
  use_delayed_data: true             # 启用延迟数据  
  historical_data_only: true         # 仅历史数据
  
  # API设置
  skip_realtime_calls: true          # 跳过实时API调用
  prefer_historical_fallback: true   # 优先历史数据fallback
  
  # 数据延迟容忍度设置
  max_data_delay_hours: 24          # 最大数据延迟24小时
  use_previous_close: true          # 使用前一日收盘价作为替代
  
  # 错误处理
  ignore_403_errors: true           # 忽略403权限错误
  auto_fallback_on_error: true      # 错误时自动fallback

# Alpha因子设置
alpha_config:
  # 数据时间点 - 避免使用实时数据
  use_t_minus_1_data: true          # 使用T-1数据避免权限问题
  data_lag_adjustment: 1            # 数据滞后调整天数
  
  # 因子类型限制
  enable_intraday_features: false   # 禁用日内因子
  focus_on_daily_features: true     # 专注日频因子
  
  # 历史数据设置
  lookback_days: 252               # 回望期1年
  min_history_days: 30             # 最少历史数据天数
  
# 数据质量设置
data_quality:
  # 延迟数据质量检查
  check_data_freshness: false       # 不检查数据新鲜度
  allow_stale_data: true           # 允许过期数据
  
  # 数据完整性要求
  require_complete_ohlcv: true     # 要求完整OHLCV数据
  fill_missing_with_previous: true # 用前值填补缺失
  
# 性能优化
performance:
  # 缓存设置
  cache_historical_data: true      # 缓存历史数据
  cache_expiry_hours: 12          # 缓存过期时间
  
  # 请求限制设置
  max_concurrent_requests: 5       # 最大并发请求数
  request_delay_ms: 200           # 请求间延迟
  
# 日志设置
logging:
  suppress_realtime_warnings: true  # 抑制实时数据警告
  log_fallback_usage: true         # 记录fallback使用情况

# 仅技术因子配置 - 无基本面数据
alphas:
  # 动量因子
  - name: "momentum_1d"
    function: "momentum"
    period: 1
    decay: 8
    enabled: true
  
  - name: "momentum_5d" 
    function: "momentum"
    period: 5
    decay: 12
    enabled: true
    
  - name: "momentum_20d"
    function: "momentum" 
    period: 20
    decay: 15
    enabled: true
    
  # 均值回归因子
  - name: "mean_reversion_5d"
    function: "mean_reversion"
    period: 5
    decay: 10
    enabled: true
    
  - name: "mean_reversion_20d"
    function: "mean_reversion"
    period: 20
    decay: 15
    enabled: true
    
  # 波动率因子
  - name: "volatility_5d"
    function: "volatility"
    period: 5
    decay: 8
    enabled: true
    
  - name: "volatility_20d"
    function: "volatility"
    period: 20
    decay: 12
    enabled: true
    
  # 成交量因子
  - name: "volume_ratio"
    function: "volume_ratio"
    period: 20
    decay: 10
    enabled: true
    
  - name: "volume_trend"
    function: "volume_trend"
    period: 10
    decay: 8
    enabled: true
    
  # 技术指标因子
  - name: "rsi_14d"
    function: "rsi"
    period: 14
    decay: 12
    enabled: true
    
  - name: "price_position"
    function: "price_position"
    period: 20
    decay: 12
    enabled: true

  # 动量因子扩展
  - name: "reversal_5d"
    function: "reversal_5"
    period: 5
    decay: 8
    enabled: true

  - name: "momentum_6_1"
    function: "momentum_6_1"
    period: 21
    decay: 12
    enabled: true

  - name: "residual_momentum"
    function: "residual_momentum"
    period: 60
    decay: 18
    enabled: true

  - name: "new_high_proximity"
    function: "new_high_proximity"
    period: 252
    decay: 25
    enabled: true

  # 技术指标因子扩展
  - name: "technical_sma_20"
    function: "technical_sma_20"
    period: 20
    decay: 12
    enabled: true

  - name: "technical_macd"
    function: "technical_macd"
    period: 26
    decay: 10
    enabled: true

  - name: "technical_bb_position"
    function: "technical_bb_position"
    period: 20
    decay: 8
    enabled: true

  # 风险因子 (基于价格历史)
  - name: "low_beta"
    function: "low_beta"
    period: 252
    decay: 45
    enabled: true

  - name: "idiosyncratic_vol"
    function: "idiosyncratic_vol"
    period: 60
    decay: 15
    enabled: true

  - name: "risk_max_drawdown"
    function: "risk_max_drawdown"
    period: 252
    decay: 30
    enabled: true

  # 流动性因子 (基于交易数据)
  - name: "amihud_illiquidity"
    function: "amihud"
    period: 21
    decay: 12
    enabled: true

  - name: "bid_ask_spread"
    function: "bid_ask_spread"
    period: 21
    decay: 12
    enabled: true

  - name: "volume_turnover"
    function: "volume_turnover"
    period: 21
    decay: 12
    enabled: true

  # 价格模式因子
  - name: "gap_momentum"
    function: "gap_momentum"
    period: 10
    decay: 8
    enabled: true

  - name: "intraday_momentum"
    function: "intraday_momentum"
    period: 5
    decay: 5
    enabled: true

# Alpha处理设置
processing:
  winsorize_quantiles: [0.01, 0.99]
  standardization: "cross_sectional"
  neutralization:
    by_industry: false
    by_market_cap: false
  
# 性能设置  
performance:
  cache_enabled: true
  parallel_processing: true
  max_workers: 2  # 降低并发数避免API限制