# Proper Training Configuration for BMA Model
# This configuration enables full cross-validation and proper training

model_config:
  # Enable cross-validation
  enable_cv: true
  cv_splits: 5
  use_purged_cv: true
  
  # Time series specific
  embargo_days: 10
  purge_days: 10
  
  # Feature selection
  feature_selection_method: "rolling_ic"
  max_features: 50
  min_ic_threshold: 0.02
  
  # Model training
  enable_hyperparameter_tuning: true
  n_jobs: -1  # Use all CPU cores
  
training:
  # Traditional models
  models:
    elastic_net:
      enabled: true
      cv_splits: 5
      alphas: [0.001, 0.01, 0.1, 1.0]
      l1_ratios: [0.1, 0.5, 0.7, 0.9]
      
    xgboost:
      enabled: true
      cv_splits: 5
      n_estimators: [100, 200, 300]
      max_depth: [3, 5, 7]
      learning_rate: [0.01, 0.05, 0.1]
      
    lightgbm:
      enabled: true
      cv_splits: 5
      n_estimators: [100, 200, 300]
      num_leaves: [31, 50, 100]
      learning_rate: [0.01, 0.05, 0.1]
      
  # Stacking configuration
  stacking:
    enabled: true
    cv_splits: 3
    use_probabilities: false
    
  # Validation
  validation:
    method: "time_series_split"
    n_splits: 5
    test_size: 0.2
    gap: 10  # days gap between train and test
    
# Performance settings
performance:
  # Memory optimization
  chunk_size: 10000
  enable_memory_optimization: true
  
  # Parallel processing
  n_jobs: -1
  backend: "threading"
  
  # Caching
  enable_caching: true
  cache_dir: "./cache"
  
# Production settings  
production:
  # Minimum requirements
  min_training_samples: 10000
  min_cv_score: 0.01
  min_ic: 0.02
  
  # Risk controls
  max_position_size: 0.05
  max_leverage: 1.0
  
  # Monitoring
  enable_logging: true
  log_level: "INFO"
  save_models: true
  model_dir: "./models"