# EOD Trading Configuration
# 收盘后信号生成 + 次日开盘下单模式配置

# 策略配置
strategy:
  double_trend:
    eod_mode: true                    # 只在收盘后跑信号
    run_after_close_min: 20           # 收盘后等20分钟触发，避免15分钟延迟
    
  execution:
    open_order_type: "LOO"            # 首选开盘限价单；也支持 "MOO"
    avoid_open_auction: false         # 如需避开开盘竞价阶段，改成 true
    limit_band_by_atr_mult: 0.5       # 开仓价带 = 0.5×ATR
    limit_band_floor_pct: 0.003       # 价带地板=0.30%
    limit_band_cap_pct: 0.015         # 价带上限=1.5%
    cancel_if_not_filled_minutes: 30  # 开盘后30分钟未成撤单

# 风险管理配置
risk_management:
  default_stop_pct: 0.01             # 初始止损1%
  
  atr_trailing:
    enabled: true                     # 启用ATR移动止损
    period: 14                        # ATR计算期间
    multiplier: 2.0                   # ATR倍数
    activate_after_R: 1.0             # 浮盈>=1R时激活
    eod_update_only: true             # 只在EOD更新移动止损

# 仓位管理配置
sizing:
  per_trade_risk_pct: 0.005          # 延迟环境建议单笔风险0.5%
  max_position_pct_of_equity: 0.10   # 单仓位最大10%资金
  base_dollar_amount: 10000          # 基础下单金额

# 交易时间配置
timing:
  market_open_time: "09:30"          # 美股开盘时间
  market_close_time: "16:00"         # 美股收盘时间
  eod_signal_delay_min: 20           # 收盘后延迟时间
  
# 数据源配置
data_sources:
  primary: "polygon"                  # 主要数据源
  backup: "yahoo"                     # 备用数据源
  daily_bars_lookback: 200           # 日线数据回溯天数
  
# 订单执行配置
order_execution:
  default_exchange: "SMART"          # 默认交易所
  currency: "USD"                    # 交易货币
  enable_risk_validation: true       # 启用风控校验
  enable_audit_logging: true         # 启用审计日志
  
# 日志配置
logging:
  level: "INFO"
  enable_trade_audit: true
  enable_performance_metrics: true
  
# 监控配置
monitoring:
  enable_alerts: true
  alert_channels: ["email", "log"]
  track_execution_metrics: true