#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Print bucketed average returns (Top/Bottom rank buckets) from a performance_report_*.csv
generated by scripts/comprehensive_model_backtest.py.

Example:
  python scripts/print_bucket_summary.py --output-dir results/full_bucket_10x150_<SID> --max-rank 150 --step 10
"""

from __future__ import annotations

import argparse
import glob
import os
from typing import List, Tuple

import pandas as pd


def _make_buckets(max_rank: int, step: int) -> List[Tuple[int, int]]:
    max_rank = max(1, int(max_rank))
    step = max(1, int(step))
    out: List[Tuple[int, int]] = []
    s = 1
    while s <= max_rank:
        e = min(max_rank, s + step - 1)
        out.append((s, e))
        s = e + 1
    return out


def _latest_report(output_dir: str) -> str:
    reports = sorted(glob.glob(os.path.join(output_dir, "performance_report_*.csv")))
    if not reports:
        raise FileNotFoundError(f"No performance_report_*.csv found under: {output_dir}")
    return reports[-1]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--report", type=str, default=None, help="Path to performance_report_*.csv")
    ap.add_argument("--output-dir", type=str, default=None, help="Directory containing performance_report_*.csv")
    ap.add_argument("--max-rank", type=int, default=150)
    ap.add_argument("--step", type=int, default=10)
    ap.add_argument("--models", type=str, default=None, help="Comma-separated model names to print (default: all in report)")
    args = ap.parse_args()

    if args.report:
        report_path = args.report
    elif args.output_dir:
        report_path = _latest_report(args.output_dir)
    else:
        ap.error("Provide --report or --output-dir")
        return 2

    df = pd.read_csv(report_path)
    if "Model" not in df.columns:
        raise ValueError(f"Missing 'Model' column in report: {report_path}")

    buckets = _make_buckets(args.max_rank, args.step)

    if args.models:
        wanted = [m.strip() for m in args.models.split(",") if m.strip()]
        df = df[df["Model"].astype(str).isin(wanted)].copy()

    print(f"REPORT: {report_path}")
    for _, row in df.iterrows():
        model = str(row["Model"])
        print(f"\n{model}")

        top_parts = []
        for s, e in buckets:
            k = f"avg_top_{s}_{e}_return"
            v = row.get(k, float("nan"))
            try:
                v = float(v)
            except Exception:
                v = float("nan")
            top_parts.append(f"T{s:03d}-{e:03d}:{v: .6f}%")

        bot_parts = []
        for s, e in buckets:
            k = f"avg_bottom_{s}_{e}_return"
            v = row.get(k, float("nan"))
            try:
                v = float(v)
            except Exception:
                v = float("nan")
            bot_parts.append(f"B{s:03d}-{e:03d}:{v: .6f}%")

        print("  TOP    " + " | ".join(top_parts))
        print("  BOTTOM " + " | ".join(bot_parts))

    return 0


if __name__ == "__main__":
    raise SystemExit(main())


